# Generated by Django 3.1.2 on 2022-04-05 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=15, verbose_name='氏名（姓）')),
                ('first_name', models.CharField(max_length=15, verbose_name='氏名（名）')),
                ('reservation_date', models.DateTimeField(verbose_name='予約日時')),
                ('reservation_count', models.IntegerField(verbose_name='予約人数')),
                ('tell', models.CharField(max_length=12, verbose_name='電話番号')),
                ('celebration_existence', models.IntegerField(max_length=1, verbose_name='お祝い有無')),
                ('demand', models.TextField(verbose_name='要望')),
                ('created_at', models.DateTimeField(verbose_name='登録日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
