# Generated by Django 3.1.2 on 2022-04-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='celebration_existence',
            field=models.IntegerField(verbose_name='お祝い有無'),
        ),
    ]
