# Generated by Django 3.1.2 on 2022-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20220405_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
